### ISSUE TITLE
does not work in Safari

### ISSUE THREAD

**Issue by kindohm** [kindohm/masher#9]
Fails with:

```
InvalidStateError: The object is in an invalid state.
```

when calling `.play()`:

```
src/Scene1.js:128
  125 |   }
  126 | 
  127 |   accent ? this.currentAccent.play() : this.currentDrum.play();
> 128 |   this.currentSynth.play();
  129 |   this.lastTriggeredSynth = this.currentSynth;
  130 | }
  131 | 
```

Discovered in https://github.com/kindohm/masher/pull/8

Related to https://github.com/processing/p5.js-sound/issues/357

**Comment by calumgunn** [comment]
Same problem occurs on iOS Safari - as tested in iOS Simulator.

Guess we have to fix it...

**Comment by calumgunn** [comment]
Okay, this is related to playing two sounds at once.

**Comment by calumgunn** [comment]
Thinking out loud; I see two options.
- Move to straight-up using the Web Audio API instead of p5's abstraction of it. I'm not sure if this will fix anything, though.
- New mp3s of combined drum/synth, that we only use in Safari.

I'll give the first one a shot at some point this weekend to check it out.

**Comment by kindohm** [comment]
Should be able to quickly test the Web Audio API theory with a simple little prototype in Safari. Or just try and implement it in this app.

If we end up going with the 2nd option, it would be easier to just have all browsers use the combined drum/synth samples. I think the sub-groups of synths always use the same drum samples, so combining the layers wouldn't remove any audible functionality that we already have (I don't think).

I would prefer going with option #1 instead of re-working the samples.

**Comment by calumgunn** [comment]
As would I!
